server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://microservice.db.iwinv.net:3306/microservice?serverTimezone=UTC
    username: microservice
    password: EK'[KD#*2AHR-c_E
  jpa:    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        id.new_generator_mappings: false
  freemarker:    template-loader-path:    - classpath:/templates/
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
